name: Publish Docker image to Docker Hub

on:
  push:
    paths-ignore:
      - 'scripts/***'
      - 'tests/***'
      - '.gitignore'
      - 'docker-compose-dev.yaml'
      - 'docker-compose.yaml'
      - 'README.md'
    branches:
      - main

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t guihbc/rinha-de-backend-2024-q1 .

    - name: Push Docker image to Docker Hub
      run: docker push guihbc/rinha-de-backend-2024-q1